---
# Register a RHEL-based system with subscription-manager.

- name: Set entitlements_path
  set_fact:
    entitlements_path: "{{ secrets_path }}/entitlements.yml"

- name: Include Red Hat encrypted variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ entitlements_path }}"
    - empty.yml
  no_log: true
  tags:
    - vars

- name: Set have_entitlements
  set_fact:
    have_entitlements: "{{ subscription_manager_org != '' and subscription_manager_activationkey != ''}}"

- name: Install CA Cert from Satellite Server
  yum:
    name: "{{ satellite_cert_rpm }}"
    state: present
    validate_certs: no
  when: use_satellite == true

- name: Determine if node is registered with subscription-manager.
  command: subscription-manager identity
  register: subscription
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Set rhsm_registered if we're already registered
  set_fact:
    rhsm_registered: "{{ subscription.rc == 0 }}"

- name: Register with subscription-manager.
  command: subscription-manager register
           --activationkey={{ subscription_manager_activationkey }}
           --org={{ subscription_manager_org }}
  no_log: true
  when: rhsm_registered == false and have_entitlements == true
  register: entitled
  until: entitled|success
  retries: 5
  delay: 10

- name: Set rhsm_registered if we just registered
  set_fact:
    rhsm_registered: true
  when: entitled|success

# Output of this command is, for example:
# 7.1
# 7.2
# 7Server
- name: List CDN releases available to system
  shell: "subscription-manager release --list | grep -E '[0-9]'"
  register: rhsm_release_list
  changed_when: false
  failed_when: rhsm_release_list.rc != 0 and "Beta" not in ansible_lsb.description

# We don't need to be registered to CDN since there's no packages available
# for this Beta/Alpha/RC installation
- name: Unregister Beta/Alpha/RC system with subscription-manager
  command: subscription-manager unregister
  when: ansible_distribution_version not in rhsm_release_list.stdout_lines
  register: unregistered_beta_distro
  until: unregistered_beta_distro|success
  retries: 5
  delay: 10

# Setting rhsm_registered back to false allows the rest of the playbook
# (except beta_repos.yml) to be skipped
- name: Set rhsm_registered to false if Beta/Alpha/RC release
  set_fact:
    rhsm_registered: false
  when: not unregistered_beta_distro|skipped

- name: Run beta_repos.yml playbook for Beta/Alpha/RC release
  import_tasks: beta_repos.yml
  when: ansible_distribution_version not in rhsm_release_list.stdout_lines

- name: Get list of enabled RHSM repos
  shell: subscription-manager repos --list | grep -B4 'Enabled:.*1' | grep 'Repo ID:' | sed -e 's/Repo ID:\s*\(.*\)/\1/' | sort
  register: repo_list_cmd
  when: rhsm_registered == true
  changed_when: false

- name: Store list of enabled repos
  set_fact:
    repo_list: "{{ repo_list_cmd.stdout.split('\n') }}"
  when: repo_list_cmd is defined and not repo_list_cmd|skipped

- name: Set replace_repos false if entitlements are missing or if we unregistered
  set_fact:
    replace_repos: false
  when: have_entitlements == false or unregistered_beta_distro|changed

- name: Set replace_repos true if rhsm_repos differs from repo_list
  set_fact:
    replace_repos: "{{ repo_list|sort != rhsm_repos|sort }}"
  when: repo_list is defined

- name: Set replace_repos true if newly-subscribed
  set_fact:
    replace_repos: true
  when: rhsm_registered == true and
        (entitled|changed and entitled.rc == 0)

- name: Disable all rhsm repos
  command: subscription-manager repos --disable '*'
  when: rhsm_registered == true and
        replace_repos|bool == true
  # This produces an absurd amount of useless output
  no_log: true

- name: Enable necessary rhsm repos
  command: subscription-manager repos --enable {{ item }}
  with_items: "{{ rhsm_repos }}"
  when: rhsm_registered == true and
        replace_repos|bool == true
  retries: 5
  delay: 10

- name: Remove old apt-mirror repository definition.
  file:
    path: /etc/yum.repos.d/cd.repo
    state: absent
  when: entitled|success
