---
ntp_service_name: ntp
ssh_service_name: ssh
nfs_service: nfs-kernel-server

ceph_packages_to_remove:
  - ceph
  - ceph-common
  - libcephfs1
  - radosgw
  - python-ceph
  - python-rados
  - python-cephfs
  - python-rbd
  - librbd1
  - librados2
  - ceph-fs-common-dbg
  - ceph-fs-common

packages:
    - lvm2
common_packages: []

apt_repos: []
common_apt_repos: []
